export const ErrorCode = {
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  EXAM_NOT_FOUND: 'EXAM_NOT_FOUND',
  SERIES_NOT_FOUND: 'SERIES_NOT_FOUND',
  DUPLICATE_SLUG: 'DUPLICATE_SLUG',

  TEST_NOT_FOUND: 'TEST_NOT_FOUND',
  TEST_NOT_PUBLISHED: 'TEST_NOT_PUBLISHED',
  TEST_NOT_AVAILABLE: 'TEST_NOT_AVAILABLE',
  TEST_VALIDATION_FAILED: 'TEST_VALIDATION_FAILED',
  TEST_NOT_EDITABLE: 'TEST_NOT_EDITABLE',
  TEST_INVALID_STATUS_TRANSITION: 'TEST_INVALID_STATUS_TRANSITION',

  ATTEMPT_NOT_FOUND: 'ATTEMPT_NOT_FOUND',
  ATTEMPT_ALREADY_ACTIVE: 'ATTEMPT_ALREADY_ACTIVE',
  ATTEMPT_EXPIRED: 'ATTEMPT_EXPIRED',
  ATTEMPT_ALREADY_SUBMITTED: 'ATTEMPT_ALREADY_SUBMITTED',
  ATTEMPT_LIMIT_EXCEEDED: 'ATTEMPT_LIMIT_EXCEEDED',

  SUBJECT_NOT_FOUND: 'SUBJECT_NOT_FOUND',
  TOPIC_NOT_FOUND: 'TOPIC_NOT_FOUND',

  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  QUESTION_NOT_APPROVED: 'QUESTION_NOT_APPROVED',
  QUESTION_VERSION_INVALID: 'QUESTION_VERSION_INVALID',
  INVALID_OPTION: 'INVALID_OPTION',

  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',

  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  PAYMENT_WEBHOOK_INVALID: 'PAYMENT_WEBHOOK_INVALID',

  ENTITLEMENT_NOT_FOUND: 'ENTITLEMENT_NOT_FOUND',
  ENTITLEMENT_EXPIRED: 'ENTITLEMENT_EXPIRED',

  AI_JOB_NOT_FOUND: 'AI_JOB_NOT_FOUND',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  RESULT_NOT_RELEASED: 'RESULT_NOT_RELEASED',
  RESULT_NOT_FOUND: 'RESULT_NOT_FOUND',

  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
